project:
  type: website
  preview:
    port: 5555

website:
  title: "Сайт"
  repo-url: https://github.com/materov/sample-site-ITMO
  repo-actions: [edit, issue]
  navbar:
    background: "#0D0D0D"
    pinned: true
    left:
      - href: index.qmd
        text: Основные исследования
      - href: about.qmd
        text: О сайте
    right:
      - icon: github
        href: https://github.com/materov/sample-site-ITMO
      - icon: mastodon
        href: https://mastodon.social/@Mastodon
  page-footer: 
    left: "© {{< now year >}} &#10072; Создано на {{< iconify simple-icons:quarto >}} Quarto" 
    right: |
      <span class="faux-block">[![Netlify Status](https://api.netlify.com/api/v1/badges/86aa8a71-4916-4d46-8f51-ca512935f7f3/deploy-status)](https://app.netlify.com/sites/sample-site-itmo/deploys){.external target="_blank"}</span>

format:
  html:
    toc: true
    toc-depth: 2
    theme: 
      # https://quarto.org/docs/output-formats/html-themes.html
      light: [flatly, styles_light.scss]
      dark: darkly
    # docx: 
    #   reference-doc: custom-reference-doc.docx
    #   toc: false

title-block-banner: images/banner.png

lang: ru
# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-ru.yml
language:
  title-block-affiliation-single: "Университет"
  title-block-affiliation-plural: "Университет"
  section-title-references: "Список литературы"
  section-title-abstract: "Аннотация для сайта"

code-tools:
  source: true